<?php

/**
 * Implements hook_default_search_api_server().
 *
 * Add the following overrides to settings.php as needed:
 *   - $conf['progenitor_search_host'] = 'localhost';
 *   - $conf['progenitor_search_port'] = '8983';
 *   - $conf['progenitor_search_path'] =  '/solr';
 *   - $conf['progenitor_search_scheme'] = 'https';
 *   - $conf['progenitor_search_user'] = '';
 *   - $conf['progenitor_search_pass'] = '';
 */
function progenitor_search_default_search_api_server() {
  $items = array();
  $items['search_primary'] = entity_import('search_api_server', '{
    "name" : "Search Primary",
    "machine_name" : "search_primary",
    "description" : "Configured for use of Phase2 DevCloud Search Service.",
    "class" : "search_api_solr_service",
    "options" : {
      "scheme" : "' . variable_get('progenitor_search_scheme', 'http') . '",
      "host" : "' . variable_get('progenitor_search_host', 'localhost') . '",
      "port" : "' . variable_get('progenitor_search_port', '8983') . '",
      "path" : "\\' . variable_get('progenitor_search_path', '/solr') . '",
      "http_user" : "' . variable_get('progenitor_search_user', '') . '",
      "http_pass" : "' . variable_get('progenitor_search_pass', '') . '",
      "excerpt" : 0,
      "retrieve_data" : 0,
      "highlight_data" : 0,
      "http_method" : "POST"
    },
    "enabled" : "1",
    "rdf_mapping" : []
  }');
  return $items;
}
